

CREATE TABLE TB_CARGO(
CARCOD CHAR(02) NOT NULL,
CARNOM VARCHAR(100),
USUING VARCHAR(30),
FECING DATETIMEOFFSET,
USUMOD VARCHAR(30),
FECMOD DATETIMEOFFSET,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_DOCUMENTO_IDENTIDAD(
DOCIDECOD CHAR(02) NOT NULL,
DOCIDENOM VARCHAR(50),
DOCIDEABR VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_ESTADO(
ESTCOD CHAR(02) NOT NULL,
ESTNOM VARCHAR(50),
ESTCOL VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_ETNIA(
ETNCOD CHAR(02) NOT NULL,
ETNNOM VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_FINANCIADOR(
FINCOD CHAR(02) NOT NULL,
FINNOM VARCHAR(50),
FINIDE VARCHAR(10),
FINSAP VARCHAR(10),
MONCOD CHAR(02),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_GENERO(
GENCOD CHAR(02) NOT NULL,
GENNOM VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_IMPLEMENTADOR(
IMPCOD CHAR(02) NOT NULL,
IMPNOM VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_MONEDA(
MONCOD CHAR(02) NOT NULL,
MONNOM VARCHAR(100),
MONABR VARCHAR(50),
MONSIM VARCHAR(02),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_NACIONALIDAD(
NACCOD CHAR(02) NOT NULL,
NACNOM VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)

CREATE TABLE TB_ROL(
ROLCOD CHAR(02) NOT NULL,
ROLNOM VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_TIPO_VALOR(
TIPVALCOD CHAR(02) NOT NULL,
TIPVALNOM VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TB_UNIDAD(
UNICOD CHAR(04) NOT NULL,
UNINOM VARCHAR(50),
UNIINVPER CHAR(01),
UNIDETLAB VARCHAR(100),
UNIDETPLA VARCHAR(100),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_ACTIVIDAD(
ACTANO CHAR(04) NOT NULL,
ACTCOD CHAR(06) NOT NULL,
RESANO CHAR(04),
RESCOD CHAR(06),
ACTNOM VARCHAR(600),
ACTNUM VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_BENEFICIARIO(
BENANO CHAR(04) NOT NULL,
BENCOD CHAR(06) NOT NULL,
BENNOM VARCHAR(50),
BENAPE VARCHAR(50),
BENFECNAC CHAR(10),
BENTEL VARCHAR(13),
BENCORELE VARCHAR(50),
BENSEX CHAR(01),
GENCOD CHAR(02),
BENFECREG CHAR(10),
BENCODUNI VARCHAR(13),
BENTELCON VARCHAR(13),
BENNOMAPO VARCHAR(50),
BENAPEAPO VARCHAR(50),
NACCOD CHAR(02),
BENDIR VARCHAR(100),
BENAUT CHAR(01),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_INDICADOR(
INDANO CHAR(04) NOT NULL,
INDCOD CHAR(06) NOT NULL,
ACTANO CHAR(04),
ACTCOD CHAR(06),
INDNOM VARCHAR(600),
INDNUM VARCHAR(10),
INDTIPIND CHAR(03),
UNICOD CHAR(04),
TIPVALCOD CHAR(02),
INDTOTPRE VARCHAR(10),
MONCOD CHAR(02),
INDLINBAS VARCHAR(10),
INDFOR VARCHAR(50),
INDNUMPRE VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_MENU(
MENANO CHAR(04) NOT NULL,
MENCOD CHAR(06) NOT NULL,
MENNOM VARCHAR(50),
MENREF VARCHAR(50),
MENICO VARCHAR(50),
MENORD VARCHAR(3),
MENANOPAD CHAR(04),
MENCODPAD CHAR(06),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_META(
METANO CHAR(04) NOT NULL,
METCOD CHAR(06) NOT NULL,
ESTCOD CHAR(02),
METMETTEC VARCHAR(10),
METEJETEC VARCHAR(10),
METPORAVATEC VARCHAR(10),
METMETPRE VARCHAR(10),
METEJEPRE VARCHAR(10),
METPORAVAPRE VARCHAR(10),
METMESPLATEC CHAR(02),
METANOPLATEC CHAR(04),
METMESPLAPRE CHAR(02),
METANOPLAPRE CHAR(04),
METESTPRE CHAR(01),
IMPCOD CHAR(02),
UBIANO CHAR(04),
UBICOD CHAR(06),
INDANO CHAR(04),
INDCOD CHAR(06),
USUANO CHAR(04),
USUCOD CHAR(06),
FINCOD CHAR(02),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_META_GASTO(
METGASANO CHAR(04) NOT NULL,
METGASCOD CHAR(06) NOT NULL,
METGASANOEJE CHAR(04),
METGASMESEJE CHAR(02),
METGASEJE VARCHAR(20),
IMPCOD CHAR(02),
FINCOD CHAR(02),
UBIANO CHAR(04),
UBICOD CHAR(06),
INDANO CHAR(04),
INDCOD CHAR(06),
MONCOD CHAR(02),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_META_PRESUPUESTO(
METPREANO CHAR(04) NOT NULL,
METPRECOD CHAR(06) NOT NULL,
METPREMET VARCHAR(20),
METPREEJE VARCHAR(20),
METPREPORAVA VARCHAR(10),
METPREMESPLA CHAR(02),
METPREANOPLA CHAR(04),
ESTCOD CHAR(02),
IMPCOD CHAR(02),
FINCOD CHAR(02),
UBIANO CHAR(04),
UBICOD CHAR(06),
INDANO CHAR(04),
INDCOD CHAR(06),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_OBJETIVO(
OBJANO CHAR(04) NOT NULL,
OBJCOD CHAR(06) NOT NULL,
SUBPROANO CHAR(04),
SUBPROCOD CHAR(06),
OBJNOM VARCHAR(600),
OBJNUM VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_OBJETIVO_ESPECIFICO(
OBJESPANO CHAR(04) NOT NULL,
OBJESPCOD CHAR(06) NOT NULL,
OBJANO CHAR(04),
OBJCOD CHAR(06),
OBJESPNOM VARCHAR(600),
OBJESPNUM VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_PROYECTO(
PROANO CHAR(04) NOT NULL,
PROCOD CHAR(06) NOT NULL,
PROIDE VARCHAR(10),
PROLININT VARCHAR(10),
PRONOM VARCHAR(600),
PRODES VARCHAR(600),
REPANO CHAR(04),
REPCOD CHAR(06),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_RESULTADO(
RESANO CHAR(04) NOT NULL,
RESCOD CHAR(06) NOT NULL,
OBJESPANO CHAR(04),
OBJESPCOD CHAR(06),
RESNOM VARCHAR(600),
RESNUM VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_SUB_PROYECTO(
SUBPROANO CHAR(04) NOT NULL,
SUBPROCOD CHAR(06) NOT NULL,
PROANO CHAR(04),
PROCOD CHAR(06),
SUBPRONOM VARCHAR(600),
SUBPROSAP VARCHAR(100),
SUBPROINVSUBACT CHAR(01),
USUANO CHAR(04),
USUCOD CHAR(06),
SUBPROPERANOINI CHAR(04),
SUBPROPERMESINI CHAR(02),
SUBPROPERANOFIN CHAR(04),
SUBPROPERMESFIN CHAR(02),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_UBICACION(
UBIANO CHAR(04) NOT NULL,
UBICOD CHAR(06) NOT NULL,
UBINOM VARCHAR(400),
UBITIP VARCHAR(50),
UBIANOPAD CHAR(04),
UBICODPAD CHAR(06),
UBILAT VARCHAR(50),
UBILON VARCHAR(50),
UBIDIR VARCHAR(100),
UBIEST CHAR(01),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_USUARIO(
USUANO CHAR(04) NOT NULL,
USUCOD CHAR(06) NOT NULL,
DOCIDECOD CHAR(02),
USUNUMDOC VARCHAR(20),
USUNOM VARCHAR(50),
USUAPE VARCHAR(50),
USUFECNAC CHAR(10),
USUSEX CHAR(01),
USUCORELE VARCHAR(50),
CARCOD CHAR(02),
USUTEL VARCHAR(13),
USUPAS VARCHAR(100),
USUEST CHAR(01),
USUSES CHAR(01),
ROLCOD CHAR(02),
UBIANO CHAR(04),
UBICOD CHAR(06),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_CADENA_RESULTADO(
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_CADENA_RESULTADO_FINANCIADOR(
INDANO CHAR(04) NOT NULL,
INDCOD CHAR(06) NOT NULL,
FINCOD CHAR(02) NOT NULL,
CADRESFINMETPRE VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_CADENA_RESULTADO_IMPLEMENTADOR(
INDANO CHAR(04) NOT NULL,
INDCOD CHAR(06) NOT NULL,
IMPCOD CHAR(02) NOT NULL,
CADRESIMPMETTEC VARCHAR(10),
CADRESIMPMETPRE VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_CADENA_RESULTADO_PERIODO(
INDANO CHAR(04) NOT NULL,
INDCOD CHAR(06) NOT NULL,
CADRESPERANO CHAR(04) NOT NULL,
CADRESPERMETTEC VARCHAR(10),
CADRESPERMETPRE VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_CADENA_RESULTADO_UBICACION(
INDANO CHAR(04) NOT NULL,
INDCOD CHAR(06) NOT NULL,
UBIANO CHAR(04) NOT NULL,
UBICOD CHAR(06) NOT NULL,
CADRESUBIMETTEC VARCHAR(10),
CADRESUBIMETPRE VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_DOCUMENTO_IDENTIDAD_BENEFICIARIO(
DOCIDECOD CHAR(02) NOT NULL,
BENANO CHAR(04) NOT NULL,
BENCOD CHAR(06) NOT NULL,
DOCIDEBENNUM VARCHAR(13),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_MENU_USUARIO(
MENANO CHAR(04) NOT NULL,
MENCOD CHAR(06) NOT NULL,
USUANO CHAR(04) NOT NULL,
USUCOD CHAR(06) NOT NULL,
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_META_BENEFICIARIO(
METANO CHAR(04) NOT NULL,
METCOD CHAR(06) NOT NULL,
BENANO CHAR(04) NOT NULL,
BENCOD CHAR(06) NOT NULL,
UBIANO CHAR(04) NOT NULL,
UBICOD CHAR(06) NOT NULL,
METBENEDA CHAR(02),
METBENMESEJETEC CHAR(02) NOT NULL,
METBENANOEJETEC CHAR(04) NOT NULL,
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_META_EJECUCION(
METANO CHAR(04) NOT NULL,
METCOD CHAR(06) NOT NULL,
UBIANO CHAR(04) NOT NULL,
UBICOD CHAR(06) NOT NULL,
METEJEMESEJETEC CHAR(02) NOT NULL,
METEJEANOEJETEC CHAR(04) NOT NULL,
METEJEVAL VARCHAR(10),
METEJEDET VARCHAR(600),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_META_FUENTE_VERIFICACION(
METANO CHAR(04) NOT NULL,
METCOD CHAR(06) NOT NULL,
METFUEVERNOM VARCHAR(100) NOT NULL,
METFUEVERPES VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)

CREATE TABLE TB_PERMISO(
    PERCOD CHAR(02) NOT NULL,        -- Código del permiso (01-99)
    PERNOM VARCHAR(100) NOT NULL,    -- Nombre del permiso
    PERREF VARCHAR(100) NOT NULL,    -- Referencia única del permiso
    PERDES VARCHAR(255) NULL,        -- Descripción del permiso
    USUING VARCHAR(30),
    FECING DATETIME,
    USUMOD VARCHAR(30),
    FECMOD DATETIME,
    ESTREG CHAR(1),
    
    -- Definir PK
    CONSTRAINT PK_TB_PERMISO PRIMARY KEY (PERCOD)
);

CREATE TABLE TV_PERMISO_USUARIO(
    USUANO CHAR(04) NOT NULL,    -- FK a TM_USUARIO
    USUCOD CHAR(06) NOT NULL,    -- FK a TM_USUARIO
    MENANO CHAR(04) NOT NULL,    -- FK a TM_MENU
    MENCOD CHAR(06) NOT NULL,    -- FK a TM_MENU
    PERCOD CHAR(02) NOT NULL,    -- FK a TB_PERMISO
    USUING VARCHAR(30),
    FECING DATETIME,
    USUMOD VARCHAR(30),
    FECMOD DATETIME,
    ESTREG CHAR(1),
    
    -- Definir PK compuesta
    CONSTRAINT PK_TV_PERMISO_USUARIO PRIMARY KEY (USUANO, USUCOD, MENANO, MENCOD, PERCOD),
    
    -- FK con TM_USUARIO
    CONSTRAINT FK_TV_PERMISO_USUARIO_USUARIO FOREIGN KEY (USUANO, USUCOD) 
        REFERENCES TM_USUARIO(USUANO, USUCOD),
        
    -- FK con TM_MENU
    CONSTRAINT FK_TV_PERMISO_USUARIO_MENU FOREIGN KEY (MENANO, MENCOD) 
        REFERENCES TM_MENU(MENANO, MENCOD),
        
    -- FK con TB_PERMISO
    CONSTRAINT FK_TV_PERMISO_USUARIO_PERMISO FOREIGN KEY (PERCOD) 
        REFERENCES TB_PERMISO(PERCOD),
        
    -- FK compuesta con TV_MENU_PERMISO (debe existir la relación menu-permiso)
    CONSTRAINT FK_TV_PERMISO_USUARIO_MENU_PERMISO FOREIGN KEY (MENANO, MENCOD, PERCOD) 
        REFERENCES TV_MENU_PERMISO(MENANO, MENCOD, PERCOD)
);

CREATE TABLE TV_MENU_PERMISO(
    MENANO CHAR(04) NOT NULL,    -- FK a TM_MENU
    MENCOD CHAR(06) NOT NULL,    -- FK a TM_MENU
    PERCOD CHAR(02) NOT NULL,    -- FK a TB_PERMISO
    USUING VARCHAR(30),
    FECING DATETIME,
    USUMOD VARCHAR(30),
    FECMOD DATETIME,
    ESTREG CHAR(1),
    
    -- Definir PK compuesta
    CONSTRAINT PK_TV_MENU_PERMISO PRIMARY KEY (MENANO, MENCOD, PERCOD),
    
    -- FK con TM_MENU
    CONSTRAINT FK_TV_MENU_PERMISO_MENU FOREIGN KEY (MENANO, MENCOD) 
        REFERENCES TM_MENU(MENANO, MENCOD),
        
    -- FK con TB_PERMISO
    CONSTRAINT FK_TV_MENU_PERMISO_PERMISO FOREIGN KEY (PERCOD) 
        REFERENCES TB_PERMISO(PERCOD)
);

CREATE TABLE TV_ROL_MENU(
    ROLCOD CHAR(02) NOT NULL,
    MENANO CHAR(04) NOT NULL,
    MENCOD CHAR(06) NOT NULL,
    USUING VARCHAR(30),
    FECING DATETIME,
    ZONING VARCHAR(30),
    USUMOD VARCHAR(30),
    FECMOD DATETIME,
    ZONMOD VARCHAR(30),
    ESTREG CHAR(1),
    
    -- Definir PK compuesta
    CONSTRAINT PK_TV_ROL_MENU PRIMARY KEY (ROLCOD, MENANO, MENCOD),

    -- Definir FK con TB_ROL
    CONSTRAINT FK_TV_ROL_MENU_ROL FOREIGN KEY (ROLCOD) 
        REFERENCES TB_ROL(ROLCOD),
        
    -- Definir FK con TM_MENU
    CONSTRAINT FK_TV_ROL_MENU_MENU FOREIGN KEY (MENANO, MENCOD) 
        REFERENCES TM_MENU(MENANO, MENCOD)
)
 
CREATE TABLE TV_ROL_PERMISO(
    ROLCOD CHAR(02) NOT NULL,
    MENANO CHAR(04) NOT NULL,
    MENCOD CHAR(06) NOT NULL,
    PERCOD CHAR(02) NOT NULL,
    USUING VARCHAR(30),
    FECING DATETIME,
    ZONING VARCHAR(30),
    USUMOD VARCHAR(30),
    FECMOD DATETIME,
    ZONMOD VARCHAR(30),
    ESTREG CHAR(1),

    -- Definir PK compuesta
    CONSTRAINT PK_TV_ROL_PERMISO PRIMARY KEY (ROLCOD, MENANO, MENCOD, PERCOD),

    -- Definir FK con TB_ROL
    CONSTRAINT FK_TV_ROL_PERMISO_ROL FOREIGN KEY (ROLCOD) 
        REFERENCES TB_ROL(ROLCOD),
        
    -- Definir FK con TM_MENU
    CONSTRAINT FK_TV_ROL_PERMISO_MENU FOREIGN KEY (MENANO, MENCOD) 
        REFERENCES TM_MENU(MENANO, MENCOD),
        
    -- Definir FK con TB_PERMISO
    CONSTRAINT FK_TV_ROL_PERMISO_PERMISO FOREIGN KEY (PERCOD) 
        REFERENCES TB_PERMISO(PERCOD)
)

CREATE TABLE TV_SUB_PROYECTO_FINANCIADOR(
SUBPROANO CHAR(04) NOT NULL,
SUBPROCOD CHAR(06) NOT NULL,
FINCOD CHAR(02) NOT NULL,
USUING VARCHAR(30),
FECING DATETIME,
ZONING VARCHAR(30),
USUMOD VARCHAR(30),
FECMOD DATETIME,
ZONMOD VARCHAR(30),
ESTREG CHAR(1)
)
 
CREATE TABLE TV_SUB_PROYECTO_FUENTE_VERIFICACION(
SUBPROANO CHAR(04) NOT NULL,
SUBPROCOD CHAR(06) NOT NULL,
SUBPROFUEVERNOM VARCHAR(100) NOT NULL,
SUBPROFUEVERPES VARCHAR(10),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_SUB_PROYECTO_IMPLEMENTADOR(
SUBPROANO CHAR(04) NOT NULL,
SUBPROCOD CHAR(06) NOT NULL,
IMPCOD CHAR(02) NOT NULL,
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_SUB_PROYECTO_UBICACION(
SUBPROANO CHAR(04) NOT NULL,
SUBPROCOD CHAR(06) NOT NULL,
UBIANO CHAR(04) NOT NULL,
UBICOD CHAR(06) NOT NULL,
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_TIPO_CAMBIO_SUBPROYECTO(
SUBPROANO CHAR(04) NOT NULL,
SUBPROCOD CHAR(06) NOT NULL,
UBIANO CHAR(04) NOT NULL,
UBICOD CHAR(06) NOT NULL,
MONCODORI CHAR(02) NOT NULL,
MONCODDES CHAR(02) NOT NULL,
TIPCAMSUBANO CHAR(04) NOT NULL,
TIPCAMSUBMES CHAR(02) NOT NULL,
TIPCAMSUBTIPCAM VARCHAR(20),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_USUARIO_ACCESO(
USUANO CHAR(04) NOT NULL,
USUCOD CHAR(06) NOT NULL,
USUACCTIP VARCHAR(50) NOT NULL,
USUACCANO CHAR(04) NOT NULL,
USUACCCOD CHAR(06) NOT NULL,
USUACCPAD CHAR(200),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_PRESUPUESTO_HISTORIAL(
PREHISANO CHAR(04) NOT NULL,
PREHISCOD CHAR(06) NOT NULL,
METPREANO CHAR(04),
METPRECOD CHAR(06),
PREHISPRE VARCHAR(20),
PREHISNUEPRE VARCHAR(20),
PREHISREA VARCHAR(20),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_SOLICITUD_CAMBIO(
SOLCAMANO CHAR(04) NOT NULL,
SOLCAMCOD CHAR(06) NOT NULL,
USUANO CHAR(04),
USUCOD CHAR(06),
SOLCAMEST CHAR(01),
SOLCAMDES VARCHAR(600),
SOLCAMMOT VARCHAR(600),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_SOLICITUD_CAMBIO_DETALLE(
SOLCAMDETANO CHAR(04) NOT NULL,
SOLCAMDETCOD CHAR(06) NOT NULL,
SOLCAMANO CHAR(04),
SOLCAMCOD CHAR(06),
SOLCAMDETQUE VARCHAR(600),
SOLCAMDETTAB VARCHAR(50),
SOLCAMDETANOTAB CHAR(04),
SOLCAMDETCODTAB CHAR(06),
SOLCAMDETDES VARCHAR(600),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_TUTORIAL(
TUTANO CHAR(04) NOT NULL,
TUTCOD CHAR(06) NOT NULL,
TUTTIT VARCHAR(200),
TUTDES VARCHAR(200),
TUTURL VARCHAR(200),
TUTREF VARCHAR(50),
TUTPUB VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_REPOSITORIO(
REPANO CHAR(04) NOT NULL,
REPCOD CHAR(06) NOT NULL,
UBIANO CHAR(04),
UBICOD CHAR(06),
REPNOM VARCHAR(200),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_PROYECTO_REPOSITORIO(
PROANO CHAR(04) NOT NULL,
PROCOD CHAR(06) NOT NULL,
REPANO CHAR(04) NOT NULL,
REPCOD CHAR(06) NOT NULL,
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TV_SUB_PROYECTO_CIERRE(
SUBPROCIEANO CHAR(04) NOT NULL,
SUBPROANO CHAR(04) NOT NULL,
SUBPROCOD CHAR(06) NOT NULL,
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_VALIDACION(
VALANO CHAR(04) NOT NULL,
VALCOD CHAR(06) NOT NULL,
VALNOM VARCHAR(50),
VALAPE VARCHAR(50),
VALFECNAC CHAR(10),
VALTEL VARCHAR(13),
VALCORELE VARCHAR(50),
VALSEX CHAR(01),
VALCODUNI VARCHAR(13),
VALTELCON VARCHAR(13),
VALNOMAPO VARCHAR(50),
VALAPEAPO VARCHAR(50),
VALDIR VARCHAR(100),
VALAUT CHAR(01),
DOCIDECOD CHAR(02),
NACCOD CHAR(02),
GENCOD CHAR(02),
ETNCOD CHAR(02),
VALMESEJE CHAR(02),
VALANOEJE CHAR(04),
UBIANO CHAR(04),
UBICOD CHAR(06),
METANO CHAR(04),
METCOD CHAR(06),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE TM_CIERRE_SUB_PROYECTO(
CIESUBPROANO CHAR(04) NOT NULL,
CIESUBPROCOD CHAR(06) NOT NULL,
SUBPROANO CHAR(04),
SUBPROCOD CHAR(06),
CIESUBPROANOCIE CHAR(04),
CIESUBPROMESCIE CHAR(02),
CIESUBPROTIP VARCHAR(50),
CIESUBPROSEC VARCHAR(50),
USUING VARCHAR(30),
FECING DATETIME,
USUMOD VARCHAR(30),
FECMOD DATETIME,
ESTREG CHAR(1)
)
 
CREATE TABLE    TL_LOG
(
LOGANO        CHAR     (4),
LOGCOD        CHAR     (10),
LOGDES        VARCHAR  (3000),
LOGACC        VARCHAR  (100),
LOGIPMAQ      VARCHAR  (15),
LOGCODREG     VARCHAR  (100),
LOGNOMTAB     VARCHAR  (100),
LOGSQL        VARCHAR  (MAX),
LOGFECING     DATETIME,
LOGFECFIN     DATETIME,
LOGTIP        CHAR     (5),
USUANO        CHAR     (4),
USUCOD        CHAR     (6),
USUNOM        VARCHAR  (30),
USUAPE        VARCHAR  (30),
)
 
